### ISSUE TITLE
Contao 4 Dateibezeichnung

### ISSUE THREAD

**Issue by hoaxone** [hofff/contao-recursive-download-folder#10]
Doch noch einen Fehler gefunden.
Die Dateibezeichnung wird im Frontend nur als "LINK" beschriftet. 
Ich habe 
`<?php echo $element['data']['link']; ?>`
in
`<?php echo $element['data']['name']; ?>`
geändert.

**Comment by frontendschlampe** [comment]
```<?php echo $element['data']['link']; ?>``` ist die Standard-Bezeichnung für Downloads in Contao. Ich weiß nicht, warum Contao grundsätzlich ```link``` benutzt. Ich finde auch, dass ```title``` sinnvoller ist. Aber ich habe bei Contao mal ein Ticket aufgemacht: https://github.com/contao/contao/issues/375

Aber ich bin auch gerade auf ein Problem gestoßen, dass bei manchen Files keine Bezeichnung angezeigt wird. Nach ein paar Tests habe ich herausgefunden, dass die Erweiterung nicht merkt, wenn das Feld Link in den Metadaten leer ist. Es wird wahrscheinlich nur auf ```NULL``` geprüft, aber das Feld ```meta``` in der Tabelle ```tl_files``` ist nicht ```NULL```, wenn z.B. ```title``` befüllt ist.

**Comment by frontendschlampe** [comment]
I think, it's a problem of our extension. Contao uses ```<?= $this->link ?>``` for name but it's not meta link. @dmolineus could you check please.

**Comment by dmolineus** [comment]
@frontendschlampe I adopted the behaviour of Contao here.
