### ISSUE TITLE
Folder as a ZIP

### ISSUE THREAD

**Issue by christianbarkowsky** [hofff/contao-recursive-download-folder#17]
Ein Killer-Feature war es, wenn man alle Dateien eines Verzeichnisses als ZIP downloaden könnt. 🚀

**Comment by dmolineus** [comment]
Implementiert mit https://github.com/hofff/contao-recursive-download-folder/commit/1aa0d080c64891d38f3d3ef1bf902a47dcd9fa76 als Release 3.2.0
