### ISSUE TITLE
[3.0.0] InvalidParameterException im BE bei aktivierter Suche und prepend_locale: true

### ISSUE THREAD

**Issue by ben-eSM** [hofff/contao-recursive-download-folder#18]
Wenn Contao für mehrsprachige Seiten mit prepend_locale: true konfiguriert wurde und man die Suche im Rekursiven Download Element aktiviert hat, führ das zu einer InvalidParameterException im Backend.
Grund ist, dass die Frontend addToUrl Methode aufgerufen wird, um den Reset Link für die Suche zu generieren. Bei eingeschaltetem prepend_locale, versucht Frontend Klasse dann aber, die Sprache des Page Objekts als Parameter zu setzen, welches im Backend aber nicht zur Verfügung steht. Damit ist der erforderliche _locale Parameter leer und führt zu dem Fehler.

Evtl. könnte man im BE anstatt das Frontend Template zu rendern, ja das be_wildcard Template ausgeben.

**Comment by dmolineus** [comment]
Fixed in release 3.1.0.
