### ISSUE TITLE
Nach dem Update, Artikel im BE nicht mehr aufrufbar und Fehler im FE

### ISSUE THREAD

**Issue by adelaide-x** [hofff/contao-recursive-download-folder#19]
Hi,
ich weiß leider nicht mehr, welche Version wir zuletzt hatten aber als wir unsere Contao-Installation aktualisiert haben, haben wir auch eure Erweiterung aktualisiert und seitem funktioniert sie leider nicht mehr.

Im BE, wenn wir den Artikel öffnen wollen kommt folgende Fehlermeldung:

> Compile Error: Declaration of Hofff\Contao\RecursiveDownloadFolder\Frontend\RecursiveDownloadFolderTrait::compile(): void must be compatible with Contao\ContentElement::compile()

In FE haben wir auch eine Fehlermeldung, im Log steht:

> [2019-10-28 13:56:18] request.INFO: Matched route "contao_frontend". {"route":"contao_frontend","route_parameters":{"_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_scope":"frontend","alias":"downloads","_route":"contao_frontend"},"request_uri":"http://installationsdomain.de/downloads.html","method":"GET"} []
[2019-10-28 13:56:18] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2019-10-28 13:56:18] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Declaration of Hofff\\Contao\\RecursiveDownloadFolder\\Frontend\\RecursiveDownloadFolderTrait::compile(): void must be compatible with Contao\\ContentElement::compile() at /var/www/html/pfad/zu/unserer/installation/vendor/hofff/contao-recursive-download-folder/src/Frontend/Element/RecursiveDownloadFolderElement.php:22)"} []

Könnt ihr bitte nachschauen woran es liegen kann?
Danke schön
Adelaide

**Comment by frontendschlampe** [comment]
Welche Contao Version?

**Comment by adelaide-x** [comment]
Contao-Version: 4.4.44
PHP-Version: 7.1
Erweiterungsversion: 3.1.0

**Comment by frontendschlampe** [comment]
Wir haben den Fehler gefunden: Wir nutzen eine PHP-Funktion die erst ab PHP 7.2 funktioniert. Bitte mal ein erneutes Update auf die 3.1.1

**Comment by adelaide-x** [comment]
Danke! Ich habe keine Fehlermeldung mehr.
Aber es sieht so aus, als würde das Javascript um die Ordner zu öffnen auch nicht mehr funktionieren. Es gibt dafür leider keine Fehlermeldung, die einen Hinweis geben könnte. Ich kann leider auch keinen Link schicken.
Könnt ihr bitte nachschauen oder soll ich eine neue Issue öffnen?

**Comment by frontendschlampe** [comment]
ah jo ... bitte nochmal update ... sorry ...

**Comment by adelaide-x** [comment]
Super! Vielen Dank! Jetzt funktioniert auch alles bei mir.
