### ISSUE TITLE
Add `xhtml` templates

### ISSUE THREAD

**Issue by cliffparnitzky** [hofff/contao-recursive-download-folder#2]
For correct usage, `xhtml` templates should be provided

**Comment by frontendschlampe** [comment]
do we really need xhtml templates?

**Comment by cliffparnitzky** [comment]
for compatibility this is needed (Contao will created ERRORS on XHTML pages) ... this doesn't generate special effort, only copies of the `html5` templates have to be created ...

**Comment by frontendschlampe** [comment]
ok - I just mixed it with tpl-Templates ;-)

**Comment by cliffparnitzky** [comment]
:+1:
