### ISSUE TITLE
no files visible

### ISSUE THREAD

**Issue by robvis** [hofff/contao-recursive-download-folder#20]
Guten Tag,
Ich  will gerne Recursive Downloads nutzen, aber when ich meine  *.pdf order *.csv Dateien im Folder platz von aus meine template, dan sehe ich die Dateien nicht in Recursive Downloads Pagina. CSV und PDF Dateien sind herunterladbar in die Contao settings. Die Dateien sind da im Folder. Was konnte das Problem sein. Mit standaard Contao "Downloads" habe Ich das gleiche Problem.

Hoffe Sie koennen mir helfen.
Herzlichem Gruesse,
Rob Vis

**Comment by frontendschlampe** [comment]
You can also write in English, if it's better for you?

If you have the same problem with the default Contao downloads element, then it's a problem of our extension. Maybe you can ask in one of the support channels of Contao https://contao.org/support.html Thank you
