### ISSUE TITLE
Bei Linkklick ändert sich nur die Class

### ISSUE THREAD

**Issue by hinzke** [hofff/contao-recursive-download-folder#21]
Bei einem Linkklick auf ein Downloadelement ändert sich nur die Class des Elternelements auf ".folder-open" statt den Link, zb pdf, zu öffnen.

**Comment by frontendschlampe** [comment]
Also das sollte ja nur bei einem Ordner so sein. Wir haben hier auf verschiedenen System damit grundsätzlich kein Problem. Kann es ggfs. sein, dass hier ein CSS Problem vorliegt und somit nicht das Downloadelement selbst geklickt wird, sondern die Klickfläche vom Elternelement alles andere überlagert? Welches Contao-Version? Welche Version der Erweiterung? Ggfs. Link zur Seite?

**Comment by Hollaho** [comment]
Im Javascript die Zeile

`var links = document.querySelectorAll('.hofff-recursive-download-folder-toggleable .download-element > a');`

ersetzen durch

`var links = document.querySelectorAll('.hofff-recursive-download-folder-toggleable .folder > a');`

dann funktioniert es wie gewünscht und nur noch die Ordner bekommen beim Anklicken die Klasse "folder-open" zugewiesen. (Mit ".download-element > a" werden auch die Dateien wie Ordner behandelt.)

**Comment by dmolineus** [comment]
Behoben mit Release 3.1.3
