### ISSUE TITLE
Keine Rechteverwaltung mehr bei Update von Conato 4.9.3 auf 4.9.4

### ISSUE THREAD

**Issue by jaroslawvenzke** [hofff/contao-recursive-download-folder#22]
Nach Update von Contao 4.9.3 auf 4.9.4 zeigt das Plugin (Version 3.1.3) jedem Mitglied alle Daten die unter dem "Kunden Knoten" liegen an und ignoriert die Homeverzeichnisse jedes Mitglieds. Rechte sind ausgehebelt.

**Comment by dmolineus** [comment]
Der Fehler könnte mit den Änderungen aus https://github.com/contao/contao/pull/1840 zusammenhängen, vermutlich ausgelöst durch das Zusammenspiel mit einer weiteren Erweiterung.

Gerne hätte ich folgende Informationen:

1. Lässt sich der Fehler mit dem Downloadsmodul von Contao in der selben Installation reproduzieren?
2. Tritt der Fehler auch auf, wenn nur hofff/contao-recursive-downloads-folder als Erweiterung installiert ist?
3. Lässt sich der Fehler mit dem Downloadsmodul von Contao in der Contao-Demo reproduzieren?

**Comment by dmolineus** [comment]
Siehe https://github.com/contao/contao/issues/2152

**Comment by dmolineus** [comment]
Das Verhalten muss durch eine Dritterweiterung erzeugt werden. Contao und Recursive Downloads Folder lösen den Fehler nicht aus. Darüber hinaus muss als Standardordner der übergeordnete Ordner ausgewählt worden sein. Der Fehler wird durch einen Bug in Contao, sie oben verursacht. Hier hilft temporär nur ein Downgrade oder eine Deaktivierung der verursachenden Dritterweiterugn.

**Comment by jaroslawvenzke** [comment]
Hallo David, 

erst einmal tausend Dank für das Feedback und vor allem das Kümmern. 

Ich muss gestehen, ich bin kein Backendentwickler und verstehe nicht so
viel von dem was Ihr beschreibt. Allerdings kann ich nicht
nachvollziehen welche Drittanbieter Software hier dazwischen funkt,
weshalb ich Dir mal einen Screenshot angehangen habe von meinem Contao
Content Manager. Dort siehst Du, das es nicht wirklich viel ist was dort
integriert ist. 

Was genau wäre jetzt meine Aufgabe, wie kann ich Euch unterstützen?
Ich habe im CM nur ein Update von Contao auf 4.9.4 erfolgreich
angestoßen und dann kam das Problem, das plötzlich alle Mitglieder alle
Dateien sehen konnten. 

GLG
Jarek 

Am 13.08.2020 09:38, schrieb David Molineus:

> Das Verhalten muss durch eine Dritterweiterung erzeugt werden. Contao und Recursive Downloads Folder lösen den Fehler nicht aus. Darüber hinaus muss als Standardordner der übergeordnete Ordner ausgewählt worden sein. Der Fehler wird durch einen Bug in Contao, sie oben verursacht. Hier hilft temporär nur ein Downgrade oder eine Deaktivierung der verursachenden Dritterweiterugn. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/hofff/contao-recursive-download-folder/issues/22#issuecomment-673316066
[2]

**Comment by jaroslawvenzke** [comment]
Zu Deinen Fragen...Antworten siehe INLINE... 

Am 12.08.2020 20:11, schrieb David Molineus:

> Der Fehler könnte mit den Änderungen aus contao/contao#1840 [1] zusammenhängen, vermutlich ausgelöst durch das Zusammenspiel mit einer weiteren Erweiterung. 
> 
> Gerne hätte ich folgende Informationen: 
> 
> * Lässt sich der Fehler mit dem Downloadsmodul von Contao in der selben Installation reproduzieren?
> --> ICH KENNE DAS DOWNLOAD MODUL NICHT. ES IST NUR EURER PLUGIN (NEBEN EINEM RECAPTCHA UND EINEM ANTISPAM TOOL) IM EINSATZ.
> 
> * Tritt der Fehler auch auf, wenn nur hofff/contao-recursive-downloads-folder als Erweiterung installiert ist?
> --> DAS MÜSSTE ICH TESTEN. SOLL ICH EINE GANZ SAUBERE INSTANZ VERWENDEN ODER REICHT ES AUS DIE ZWEI TOOLS DIE IM EINSATZ SIND ZU DEINSTALLIEREN?
> 
> * Lässt sich der Fehler mit dem Downloadsmodul von Contao in der Contao-Demo reproduzieren?
> --> WIE GESAGT, KENNE ES NICHT 
> 
> GLG
> Jarek 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

 

Links:
------
[1] https://github.com/contao/contao/pull/1840
[2]
https://github.com/hofff/contao-recursive-download-folder/issues/22#issuecomment-673030195
[3]

**Comment by jaroslawvenzke** [comment]
Vielen Dank!
Verstehe leider nur nicht so viel davon :) 

GLG 

Jarek 

Am 13.08.2020 09:36, schrieb David Molineus:

> Siehe contao/contao#2152 [1] 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

 

Links:
------
[1] https://github.com/contao/contao/issues/2152
[2]
https://github.com/hofff/contao-recursive-download-folder/issues/22#issuecomment-673315207
[3]

**Comment by dmolineus** [comment]
Ein entsprechender Bugfix wurde bereits für Contao gefunden (https://github.com/contao/contao/pull/2153), eine weitere Zuarbeit ist daher nicht notwendig. Solange ein neues Bugfix noch nicht released ist, ggf. zurück auf Contao 4.9.3 gehen.

**Comment by jaroslawvenzke** [comment]
Sorry, dass ich noch mal nachfrage. Was bedeutet das genau?
Es ist was gefunden und was muss man machen? 

GLG
Jarek

**Comment by frontendschlampe** [comment]
Ich habe das Ticket erstmal geschlossen, denn es war auf ein Contao Problem zurückzuführen und sollte sich mit einer Aktualisierung auf eine höhere Contao-Version erledigt haben.

**Comment by jaroslawvenzke** [comment]
Ja vielen Dank. Das hat sich tatsächlich dadurch behoben.

LG
Jarek
