### ISSUE TITLE
Fehler im BE nach Aktivierung von prepend_locale

### ISSUE THREAD

**Issue by onmarsx** [hofff/contao-recursive-download-folder#23]
Hallo, habe gerade eine Frage im Contao Community Forum gestellt, siehe
<https://community.contao.org/de/showthread.php?79099-recursive-download-folder-Fehler-im-BE-nach-Aktivierung-von-prepend_locale>

Kurz gefasst:
Nach Aktivierung vom Sprachkürzel im URL mit prepend_locale: true (eingefügt im app/config/config.yml) funktioniert die Ansicht im BE eines Artikels mit dieser Erweiterung nicht mehr:
Fehler:
Parameter "_locale" for route "contao_frontend" must match "[a-z]{2}(?:\-[A-Z]{2})?" ("" given) to generate a corresponding URL.
Im FE wird alles korrekt angezeigt.
Contao 4.9.8 und PHP 7.3.23
Danke für einen Hinweis!

**Comment by frontendschlampe** [comment]
Hey @onmarsx wir schauen uns das an.

**Comment by dmolineus** [comment]
Behoben mit Version 3.1.4.
