### ISSUE TITLE
Caption Error

### ISSUE THREAD

**Issue by gluecksgriff** [hofff/contao-recursive-download-folder#28]
Contao 4.14 Installation mit PHP 8.1

Uncaught PHP Exception ErrorException: "Warning: Undefined array key "caption"" at /vendor/hofff/contao-recursive-download-folder/src/Frontend/FileTree/BaseFileTreeBuilder.php line 317

kurzfristige Lösung, auskommentieren der Zeile:
` // 'caption'   => (string) $meta['caption'],`

**Comment by dmolineus** [comment]
Behoben in 3.3.1
