### ISSUE TITLE
Update auf Contao 5.x?

### ISSUE THREAD

**Issue by memoworker** [hofff/contao-recursive-download-folder#29]
Das hilfreiche Recursive Download Folder Plugin erleichtert uns das Verwalten von Download-Elementen.
Da wir dieses Bundle in Projekten im Einsatz haben, möchten wir wissen, ob dieses auf die nächste Contao-Version (Contao 5.x) geupdatet wird?

**Comment by dmolineus** [comment]
Version 3.3.0 supported nun auch Contao 5.
