### ISSUE TITLE
Recursove folder list geht manchmal nicht

### ISSUE THREAD

**Issue by toteph42** [hofff/contao-recursive-download-folder#30]
Hallo,
PHP 8.1.15, Contao 4.13.37, Plugin 3.2.4. 
- Artikel angelegt mit `Rekursiver Download Ordner`
- `Home-Verzeichnis verwenden` an
- Artikel Benutzergruppe zugewiesen in der auch Benutzer ist
- User logt sich ein und sieht sein ihm zugewiesenen Ordner
- Alles ok
- Zweiten Artikel angelegt  
- Alles wie oben - nur aben ein anderer Home-Ordner
- Es wird keine Datei oder Ordner angezeit
- Dateiattribute verglichen. Exakt die Gleichen.
- Zweiten Benutzer auf das Selbe Home-Verzeichnis gesetzt, wie ersten. Ergebnis: Keine Dateien.

Frage: Wie komme ich dem Fehler auf die Spur?

**Comment by dmolineus** [comment]
Dies müsste man im konkreten Projekt debuggen. Als erste wäre es interessant, ob dieses Verhalten auch mit den Contao-Downloads-Element auftritt.

**Comment by toteph42** [comment]
Ich habe heraus gefunden, was dem Fehler zu Grunde liegt. Es ist `tl_files`. Da kann man so oft wie man will Synchronisieren. Erst wenn man den Inhalt löscht (oder die auf den Download bezogenen Datensätze) und dann neu die Dateiverwaltung synchronisiert, funktioniert die Anzeige.
