### ISSUE TITLE
Alle Ebenen anzeigen

### ISSUE THREAD

**Issue by Nico0o** [hofff/contao-recursive-download-folder#6]
Coole Erweiterung!
Was mir fehlt, ist eine Checkbox die das Öffnen der Ebenen deaktiviert und sie stattdessen direkt anzeigt.

**Comment by cliffparnitzky** [comment]
Das könnte man im Template `recursive-download-folder_default` erreichen, wenn man dort in (Zeile 4 )[https://github.com/hofff/contao-recursive-download-folder/blob/master/system/modules/hofff_recursive-download-folder/templates/recursive-download-folder/recursive-download-folder_default.html5#L4] die CSS Klasse `folder-open` einfügt.

Aber als Einstell-Option im CE klungt doch auch gut, oder was denkst du @frontendschlampe ?

**Comment by frontendschlampe** [comment]
Natürlich - find ich gut! :-)

**Comment by cliffparnitzky** [comment]
Sehr schön, dann kann das noch mit in die 2.0.0
