### ISSUE TITLE
Contao 4 compatibility

### ISSUE THREAD

**Issue by nrunde** [hofff/contao-recursive-download-folder#8]
Is there something planned on contao 4 compability?

**Comment by frontendschlampe** [comment]
Actually not, because we have no client who want to use it in Contao 4 at the moment. if we get an assignment in the future, we will make the update.

**Comment by nrunde** [comment]
How much would it cost to make it compatible? Could you make me an offer?

**Comment by frontendschlampe** [comment]
Yeah ... no problem. Could you write me an email? Thank you!

**Comment by nrunde** [comment]
Thx. You could check your inbox ;)

**Comment by frontendschlampe** [comment]
yes ... thx ... you got mail :-)
