### ISSUE TITLE
Contao 4 installation erfolgreich

### ISSUE THREAD

**Issue by hoaxone** [hofff/contao-recursive-download-folder#9]
Ich habe die aktuelle Version geladen und sie im Ordner system/modules entpackt. Danach im contao-manager den cache geleert und das Install-Toll aufgerufen. Ein Datenbankupdate durchgeführt. Die Extension ist im Backend verfügbar und funktioniert im Frontend bis jetzt fehlerfrei. 

Contao 4.5.8
PHP 7.1

**Comment by frontendschlampe** [comment]
Wir sind aktuell dabei ... dev-develop ist bereits lauffähig. Zeitnah kommt eine stable.
